### ISSUE TITLE
size specification of PNG and SVG appear very different

### ISSUE THREAD

**Issue by reagle** [pandoc-ext/diagram#29]
Perhaps this is a pandoc HTML/CSS template issue, but when I switch between `png` and `svg+xml` the size of the respective outputs differs significantly. See [png](https://reagle.org/joseph/2016/min-eg/test-diagram-png.html) and [svg](https://reagle.org/joseph/2016/min-eg/test-diagram-svg.html) for how different the sizes are.

```css

img {
  max-width: 100%;
}
svg {
  height: auto;
  max-width: 100%;
}
```

<img width="1559" alt="SCR-20240814-kmte" src="https://github.com/user-attachments/assets/52452e0d-7f32-4de9-9b44-070c5b140e07">
