### ISSUE TITLE
`.mermaid-config.json` not being used

### ISSUE THREAD

**Issue by reagle** [pandoc-ext/diagram#31]
When I was using `-F mermaid-filter` it would find styling in `.mermaid-config.json`. That doesn't seem to be picked up by diagram and I don't see any documentation on what I might be doing wrong.

**Comment by reagle** [comment]
Additionally, setting the document's metadata doesn't seem to work either:

```
---
title: "The column in context"
author: "Joseph Reagle"
date: 2024-08-01
suppress-bibliography: true
diagram:
  cache: true
  engine:
    mermaid:
      mime-types: [image/svg+xml]
      theme: base
      themeVariables:
        primaryColor: "#ffffff"
        primaryTextColor: "#000000"
        primaryBorderColor: "#000000"
        lineColor: "#000000"
        secondaryColor: "#ffffff"
        tertiaryColor: "#ffffff"
---
```

**Comment by tarleb** [comment]
Sorry, this isn't supported yet, but it would be a good addition. Would you point me to some docs for this? I'm not really familiar with mermaid and its capabilities.

**Comment by reagle** [comment]
I'm a newbie myself and find it confusing, but I first went don't that path from [mermaid-filter](https://mermaid.js.org/config/theming.html).

> Mermaid cli allows you to specify additional options in a json configuration file and a css file. mermaid-filter will look in the current working directory for .mermaid-config.json and .mermaid.css and if found, pass them in to mermaid cli.

There's also these:

- https://mermaid.js.org/config/configuration.html 
- https://mermaid.js.org/config/schema-docs/config.html
- https://mermaid.js.org/config/theming.html

I would think/hope the config options would be well documented in [mermaid-cli](https://github.com/mermaid-js/mermaid-cli), but that doesn't seem to be the case.

**Comment by ngocptblaplafla** [comment]
I made an [PR](https://github.com/pandoc-ext/diagram/pull/44) adding some common params for mmdc. With themeVariables, you can write like this [example](https://mermaid.js.org/config/theming.html#customizing-themes-with-themevariables) or write an json file with option `cssFile`
Example metadata
```
diagram:
  engine:
    mermaid:
      execpath: /usr/local/bin/mmdc
      theme: default
      configFile: 'some file like https://mermaid.js.org/schemas/config.schema.json'
      cssFile: your-theme-variables.json
      puppeteerConfigFile: /etc/puppeteer-conf.json
```
