### ISSUE TITLE
Default configuration not used as fallback if one option has been changed

### ISSUE THREAD

**Issue by benabel** [pandoc-ext/diagram#42]
If you change one option configuration you must rewrite all defaults for other engines.

**Comment by tarleb** [comment]
That's by design: compiling diagrams can be a security risk, so we are very conservative about what to allow. If *any* diagram engine is configured, then all others must be marked as *enabled* explicitly. This way, when the filter adds support for a new diagram engine, the engine is *off* my default, which is important for security-oriented users who compile documents created by untrusted users.

It's enough to set the engine to `true` to enable it:

```
diagram:
  engines:
    # Compile graphviz "dot" diagrams, but not mermaid diagrams.
    graphviz: true
    mermaid: false
```
