### ISSUE TITLE
Execpath array accepts variable for dynamic patch configuration

### ISSUE THREAD

**Issue by veenone** [pandoc-ext/diagram#43]
The newly introduced execpath with array input is a great way to manage plantuml jar for document generation. However currently we need to hardcode the path of plantuml jar as below :

```yaml
--- 
diagram: 
  engine: plantuml: 
  execpath: ['java', '-jar', 'c:/tools/plantuml.jar']
  mime-types: 
    application/pdf: false 
    image/png: true 

...

```

My request is to enable dynamic path configuration, maybe using variable  so the path can be configured somewhere else (i.e: in make file, environment variable..)

Maybe the configuration will look like this:

```yaml
--- 
diagram: 
  engine: plantuml: 
  execpath: ['java', '-jar', $(TOOL_DIR)'/plantuml.jar']
  mime-types: 
    application/pdf: false 
    image/png: true 

...

```
